### ISSUE TITLE
deepin-file-manager segfault with NFS systemd idle timeout

### ISSUE THREAD

**Issue by evilzer** [linuxdeepin/developer-center#1482]
## Describe the bug

When mounting a NFS share with the fstab option x-systemd.idle-timeout it results in a crash with deepin-file-manager. The application works as intend after re-opening it again with the share also re-mounted. I'm guessing the application tries to re-mount the share to fetch some information but fails. 

## To Reproduce

1. Use systemd options in fstab for an NFS:
`noauto,x-systemd.automount,x-systemd.device-timeout=10,x-systemd.idle-timeout=5min`
2. Have deepin-file-manager recognize it an external external disk (e.g. mount it in user home or /run/media/\<user> folder).
3. Open deepin-file-manager after systemd has un-mounted the drive.

Removing `x-systemd.idle-timeout` resolves the issue.

## Expected behavior

If the share is not seen by deepin-file-manager as an external disk (in computer tab) it also works as intended even after the drive has been un-mounted. Is it possible to stop the file-manager from trying to mount the drive when it has been un-mounted? Auto-mount and external indexing are off in settings.

### Backtrace
```
#0  0x00007f1c43cdc975 in dde_file_manager::DFMSideBarDeviceItem::DFMSideBarDeviceItem(DUrl, QWidget*) () at /usr/lib/libdde-file-manager.so.1
#1  0x00007f1c43cc6888 in  () at /usr/lib/libdde-file-manager.so.1
#2  0x00007f1c42414b70 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#3  0x00007f1c43bfb826 in DAbstractFileWatcher::subfileCreated(DUrl const&) () at /usr/lib/libdde-file-manager.so.1
#4  0x00007f1c43bfb592 in DAbstractFileWatcherPrivate::handleGhostSignal(DUrl const&, void (DAbstractFileWatcher::*)(DUrl const&), DUrl const&) () at /usr/lib/libdde-file-manager.so.1
#5  0x00007f1c43bfbe19 in DAbstractFileWatcher::ghostSignal(DUrl const&, void (DAbstractFileWatcher::*)(DUrl const&), DUrl const&) () at /usr/lib/libdde-file-manager.so.1
#6  0x00007f1c439eda77 in UDiskListener::addDevice(QExplicitlySharedDataPointer<UDiskDeviceInfo>) () at /usr/lib/libdde-file-manager.so.1
#7  0x00007f1c439f0470 in UDiskListener::addMountDiskInfo(QDiskInfo const&) () at /usr/lib/libdde-file-manager.so.1
#8  0x00007f1c42414b70 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#9  0x00007f1c43d4d386 in GvfsMountManager::mount_added(QDiskInfo const&) () at /usr/lib/libdde-file-manager.so.1
#10 0x00007f1c43c29c53 in GvfsMountManager::monitor_mount_added(_GVolumeMonitor*, _GMount*) () at /usr/lib/libdde-file-manager.so.1
#11 0x00007f1c41b42caa in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#12 0x00007f1c41b30706 in  () at /usr/lib/libgobject-2.0.so.0
#13 0x00007f1c41b3489a in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#14 0x00007f1c41b355cb in g_signal_emit_by_name () at /usr/lib/libgobject-2.0.so.0
#15 0x00007f1c41b42caa in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#16 0x00007f1c41b30706 in  () at /usr/lib/libgobject-2.0.so.0
#17 0x00007f1c41b3489a in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#18 0x00007f1c41b355cb in g_signal_emit_by_name () at /usr/lib/libgobject-2.0.so.0
#19 0x00007f1c37fdc8ec in  () at /usr/lib/gio/modules/libgioremote-volume-monitor.so
#20 0x00007f1c41a57bb0 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#21 0x00007f1c41a59b11 in  () at /usr/lib/libglib-2.0.so.0
#22 0x00007f1c41a59b51 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#23 0x00007f1c424409a3 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#24 0x00007f1c423e75ec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#25 0x00007f1c423ef326 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#26 0x0000558ced8d26f2 in main ()
```

### Distro & Version

Arch Linux
deepin-wm 1.9.38-1
deepin-file-manager 1.8.2 5.0.0-1

**Comment by BLumia** [comment]
Thanks for the info!

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
