### ISSUE TITLE
V20 beta，安装synaptic和apt-xapian-index有错误！

### ISSUE THREAD

**Issue by joo** [linuxdeepin/developer-center#1821]
版本 V20 beta，last update 6.30

安装：
```
sudo apt-get install synaptic
sudo apt-get install apt-xapian-index
sudo update-apt-xapian-index -vf
```
错误信息：
```
joo@home:~$ sudo update-apt-xapian-index -vf
[sudo] joo 的密码：
Reading plugin /usr/share/apt-xapian-index/plugins/aliases.py.
Reading plugin /usr/share/apt-xapian-index/plugins/app-install.py.
Reading plugin /usr/share/apt-xapian-index/plugins/apttags.py.
Reading plugin /usr/share/apt-xapian-index/plugins/cataloged_time.py.
Reading plugin /usr/share/apt-xapian-index/plugins/debtags.py.
Reading plugin /usr/share/apt-xapian-index/plugins/descriptions.py.
Reading plugin /usr/share/apt-xapian-index/plugins/relations.py.
Reading plugin /usr/share/apt-xapian-index/plugins/sections.py.
Reading plugin /usr/share/apt-xapian-index/plugins/sizes.py.
Reading plugin /usr/share/apt-xapian-index/plugins/template.py.
Reading plugin /usr/share/apt-xapian-index/plugins/translated-desc.py.
Most recent dataset:    Mon Jul 13 00:04:46 2020.
Most recent update for: Thu Jan  1 08:00:00 1970.
Aggregating value information.
Initializing plugins.
Rebuilding Xapian index... 4% 
Traceback (most recent call last):
  File "/usr/sbin/update-apt-xapian-index", line 104, in <module>
    indexer.rebuild(opts.pkgfile)
  File "/usr/lib/python2.7/dist-packages/axi/indexer.py", line 721, in rebuild
    self.buildIndex(dbdir, generator)
  File "/usr/lib/python2.7/dist-packages/axi/indexer.py", line 696, in buildIndex
    for doc in documents:
  File "/usr/lib/python2.7/dist-packages/axi/indexer.py", line 568, in gen_documents_apt
    yield self.get_document_from_apt(pkg)
  File "/usr/lib/python2.7/dist-packages/axi/indexer.py", line 536, in get_document_from_apt
    addon.obj.index(document, pkg)
  File "/usr/share/apt-xapian-index/plugins/relations.py", line 130, in index
    self._index_rel(pfx, val, document)
  File "/usr/share/apt-xapian-index/plugins/relations.py", line 114, in _index_rel
    doc.add_term(pfx + name.split(None, 1)[0])
IndexError: list index out of range
```

**Comment by joo** [comment]
错误是apt-xapian-index软件包的插件：/usr/share/apt-xapian-index/plugins/relations.py的第114行：
将一下代码：
```
    def _index_rel(self, pfx, val, doc):
        """
        Extract all package names from @val and index them as terms with prefix
        @pfx
        """
        for name in self.re_split.split(val):
            doc.add_term(pfx + name.split(None, 1)[0])
```
改为：
    def _index_rel(self, pfx, val, doc):
        """
        Extract all package names from @val and index them as terms with prefix
        @pfx
        """
        for name in self.re_split.split(val):
            doc.add_term(pfx + name.split(' ', 1)[0])
可以修正此问题。

此错误补丁不知道是提交给apt-xapian-index的维护着，还是提交给深度的维护者。
