### ISSUE TITLE
Krita crashes on startup

### ISSUE THREAD

**Issue by joeky888** [linuxdeepin/developer-center#1982]
I am using Manjaro testing branch.

Execute:

```python
$ krita
[1]    43604 segmentation fault (core dumped)  krita
```

Stack trace:

```cpp
(gdb) bt full
#0  0x00007fffef105b1a in deepin_platform_plugin::DHighDpi::logicalDpi(QXcbScreen*) () at /usr/lib/qt/plugins/platforms/libdxcb.so
#1  0x00007ffff4f6f542 in  () at /usr/lib/libQt5Gui.so.5
#2  0x00007ffff4f1d9e3 in QWindowSystemInterface::handleScreenAdded(QPlatformScreen*, bool) () at /usr/lib/libQt5Gui.so.5
#3  0x00007fffeefe66a1 in QXcbConnection::initializeScreens() () at /usr/lib/libQt5XcbQpa.so.5
#4  0x00007fffeefc1338 in QXcbConnection::QXcbConnection(QXcbNativeInterface*, bool, unsigned int, char const*) () at /usr/lib/libQt5XcbQpa.so.5
#5  0x00007fffeefc40f5 in QXcbIntegration::QXcbIntegration(QStringList const&, int&, char**) () at /usr/lib/libQt5XcbQpa.so.5
#6  0x00007fffef0ff8b1 in deepin_platform_plugin::DPlatformIntegration::DPlatformIntegration(QStringList const&, int&, char**) ()
    at /usr/lib/qt/plugins/platforms/libdxcb.so
#7  0x00007fffef0fefc7 in DPlatformIntegrationPlugin::create(QString const&, QStringList const&, int&, char**) ()
    at /usr/lib/qt/plugins/platforms/libdxcb.so
#8  0x00007ffff4f3c627 in QGuiApplicationPrivate::createPlatformIntegration() () at /usr/lib/libQt5Gui.so.5
#9  0x00007ffff4f3dae1 in QGuiApplicationPrivate::createEventDispatcher() () at /usr/lib/libQt5Gui.so.5
#10 0x00007ffff4b74936 in QCoreApplicationPrivate::init() () at /usr/lib/libQt5Core.so.5
#11 0x00007ffff4f40b20 in QGuiApplicationPrivate::init() () at /usr/lib/libQt5Gui.so.5
#12 0x00007ffff4f41a88 in QGuiApplication::QGuiApplication(int&, char**, int) () at /usr/lib/libQt5Gui.so.5
#13 0x00007ffff6f6f074 in KisOpenGLModeProber::probeFormat(KisOpenGL::RendererConfig const&, bool) () at /usr/lib/libkritaui.so.20
#14 0x00007ffff6f5702c in KisOpenGL::selectSurfaceConfig(KisOpenGL::OpenGLRenderer, KisConfig::RootSurfaceFormat, bool) ()
    at /usr/lib/libkritaui.so.20
#15 0x0000555555e26e2d in main ()
```

**Comment by RigoLigoRLC** [comment]
confirmed, this is related to dde qt5 integration package. im using kde so i removed deepin components, now it is fine for me. you can open an issue in the corresponding repository, maybe.

**Comment by RigoLigoRLC** [comment]
confirmed, this is related to dde qt5 integration package. im using kde so i removed deepin components, now it is fine for me. you can open an issue in the corresponding repository, maybe.

**Comment by joeky888** [comment]
[Krita from snapcraft](https://snapcraft.io/krita) is also crashing on startup.

**Comment by babyfengfjx** [comment]
Is this still a problem at the moment?

**Comment by RigoLigoRLC** [comment]
Issue is not present anymore.

babyfengfjx ***@***.***> 于 2022年1月4日周二 下午1:58写道：

**Comment by babyfengfjx** [comment]
thanks for your deedback ,If there are other questions later, thanks to continue feedback.
