### ISSUE TITLE
[Arch Linux] Deepin Movie doesn't work: AttributeError @ 'font_utils.py' 

### ISSUE THREAD

**Issue by gustavodlima** [linuxdeepin/developer-center#212]
Traceback (most recent call last):
  File "/usr/share/deepin-movie/utils/utils.py", line 376, in getSystemFonts
    return font_utils.getSystemFonts()
  File "/usr/share/deepin-movie/utils/font_utils.py", line 141, in getSystemFonts
    return fontsByLocale(locale.getdefaultlocale()[0])
  File "/usr/share/deepin-movie/utils/font_utils.py", line 87, in fontsByLocale
    locale = locale.lower().replace("_", "-")
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by hualet** [comment]
Show me the output of locale command on your computer ?

**Comment by gustavodlima** [comment]
@hualet Oh, I see. I've fixed it by using `localectl set-locale [LOCALE]`. Thanks!
