### ISSUE TITLE
After latest update ... Deepin Login 'Verification Successful' ... but loops back to the login screen !

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#2134]
Hi,

I ran the available updates on my brother Lenovo B40 laptop which wasn't updated for long after havving installed V20 on it.

after the updates yesterday i no longer able to login to the system ... I enter the password at the login screen and it says 'Verification Successful' taking it to a screen where it seems its logging in but then it shows 'Lenovo' splash screen and goes back to the login screen.

This is a loop no matter how many times i try entering the password at the login prompt !!!

Any help in resolving this issue is most appreciated.

thanks.

**Comment by aiamuzz** [comment]
I tried to record the error message that shows up in the log after the password was entered successfully ...

```
ACPI BIOS Error (bug): Could not resolve symbol [\SB_.PC10.GFX0.DD02._BCL], AE_NOT_FOUND (20190816/psargs-330)
ACPI Error: Aborting method \SB_.PC10.RP05.PEGP.DD02._BCL due to previous error (AE_NOT_FOUND) (20190816/psparse-531)
```
If this helps identify the issue ...

**Comment by justforlxz** [comment]
can you login with tty? and run this command:

```shell
cat ~/.xsession-errors
```

and take a final photo， maybe we will see some useful information

**Comment by aiamuzz** [comment]
> can you login with tty? and run this command 

by tty ... you mean logging into the command line by invoking `Ctrl+Alt+F3` ???

please find the file enlcosed ...


```
Xsession: X session started for zuni at Thu 22 Jul 2021 10:55:33 PM IST
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting DISPLAY=:0
dbus-update-activation-environment: setting XAUTHORITY=/home/zuni/.Xauthority
localuser:zuni being added to access control list
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting USER=zuni
dbus-update-activation-environment: setting LANGUAGE=en_US
dbus-update-activation-environment: setting XDG_SESSION_TYPE=x11
dbus-update-activation-environment: setting XDG_CACHE_HOME=/home/zuni/.cache
dbus-update-activation-environment: setting HOME=/home/zuni
dbus-update-activation-environment: setting QT4_IM_MODULE=fcitx
dbus-update-activation-environment: setting DESKTOP_SESSION=deepin
dbus-update-activation-environment: setting XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting IM_CONFIG_PHASE=1
dbus-update-activation-environment: setting LOGNAME=zuni
dbus-update-activation-environment: setting GTK_IM_MODULE=fcitx
dbus-update-activation-environment: setting XDG_SESSION_CLASS=user
dbus-update-activation-environment: setting PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin
dbus-update-activation-environment: setting XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
dbus-update-activation-environment: setting XDG_RUNTIME_DIR=/run/user/1000
dbus-update-activation-environment: setting DISPLAY=:0
dbus-update-activation-environment: setting LANG=en_US.UTF-8
dbus-update-activation-environment: setting XDG_SESSION_DESKTOP=deepin
dbus-update-activation-environment: setting XAUTHORITY=/home/zuni/.Xauthority
dbus-update-activation-environment: setting XDG_DATA_HOME=/home/zuni/.local/share
dbus-update-activation-environment: setting XDG_CONFIG_HOME=/home/zuni/.config
dbus-update-activation-environment: setting XMODIFIERS=@im=fcitx
dbus-update-activation-environment: setting XDG_GREETER_DATA_DIR=/var/lib/lightdm/data/zuni
dbus-update-activation-environment: setting SHELL=/bin/bash
dbus-update-activation-environment: setting GDMSESSION=deepin
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
dbus-update-activation-environment: setting QT_IM_MODULE=fcitx
dbus-update-activation-environment: setting PWD=/home/zuni
dbus-update-activation-environment: setting CLUTTER_IM_MODULE=fcitx
<warning> utils.go:222: Not found this schema: com.deepin.dde.startdde

(process:6005): GLib-GIO-ERROR **: 22:55:35.363: Settings schema 'com.deepin.dde.display' is not installed
SIGTRAP: trace trap
PC=0x7f0ad6bb5c75 m=10 sigcode=128

goroutine 0 [idle]:
runtime: unknown pc 0x7f0ad6bb5c75
stack: frame={sp:0x7f0abaffc4e0, fp:0x0} stack=[0x7f0aba7fcf48,0x7f0abaffcb48)
00007f0abaffc3e0:  000000000000003a  b85d9a16de3d8600 
00007f0abaffc3f0:  0000000000000001  00007f0ad6227680 
00007f0abaffc400:  00007f0aa0015640  0000000000000004 
00007f0abaffc410:  0000000000000004  00007f0ad6bb84b0 
00007f0abaffc420:  0000000000000000  00007f0ad6bb844a 
00007f0abaffc430:  00007f0aa0014174  0000000000000004 
00007f0abaffc440:  0000000000000004  00007f0abaffc4f0 
00007f0abaffc450:  0000000000000000  00007f0ad6bb8522 
00007f0abaffc460:  0000000000000000  0000000000000004 
00007f0abaffc470:  00007f0aa0011be0  0000000000000000 
00007f0abaffc480:  00007f0abaffc4f0  00007f0ad6bf9afc 
00007f0abaffc490:  0000000000000004  0000000000000000 
00007f0abaffc4a0:  0000000000000004  00007f0ad6bb68e5 
00007f0abaffc4b0:  0000000000000000  0000000000000000 
00007f0abaffc4c0:  0000000000000004  0000000000000004 
00007f0abaffc4d0:  0000000000000004  00007f0ad6bb5c68 
00007f0abaffc4e0: <0000000000000000  00007f0ad6bb6d0d 
00007f0abaffc4f0:  00007f0ad6c0565a  00007f0ad6c5caa2 
00007f0abaffc500:  ffffffffffffffff  00007f0ad6c0558f 
00007f0abaffc510:  00007f0aa0014110  ffffffffffffffff 
00007f0abaffc520:  00007f0ad6c055a2  00007f0ad6bff21b 
00007f0abaffc530:  ffffffffffffffff  00007f0ad6c055fc 
00007f0abaffc540:  00007f0ad66d84e7  ffffffffffffffff 
00007f0abaffc550:  0000000000000000  b85d9a16de3d8600 
00007f0abaffc560:  0000000000000004  00007f0ad6bb6f5f 
00007f0abaffc570:  00007f0aa0014110  00000001a00018b0 
00007f0abaffc580:  00007f0ad6bb6c60  0000000000000000 
00007f0abaffc590:  00007f0ad66d84e7  00007f0ad66d84e7 
00007f0abaffc5a0:  00007f0aa0004d20  00007f0aa00018b0 
00007f0abaffc5b0:  00007f0aa0004d20  00007f0aa0004d30 
00007f0abaffc5c0:  0000000000000000  00007f0ad65a12e0 
00007f0abaffc5d0:  00007f0aa0001c10  00007f0ad6561d93 
runtime: unknown pc 0x7f0ad6bb5c75
stack: frame={sp:0x7f0abaffc4e0, fp:0x0} stack=[0x7f0aba7fcf48,0x7f0abaffcb48)
00007f0abaffc3e0:  000000000000003a  b85d9a16de3d8600 
00007f0abaffc3f0:  0000000000000001  00007f0ad6227680 
00007f0abaffc400:  00007f0aa0015640  0000000000000004 
00007f0abaffc410:  0000000000000004  00007f0ad6bb84b0 
00007f0abaffc420:  0000000000000000  00007f0ad6bb844a 
00007f0abaffc430:  00007f0aa0014174  0000000000000004 
00007f0abaffc440:  0000000000000004  00007f0abaffc4f0 
00007f0abaffc450:  0000000000000000  00007f0ad6bb8522 
00007f0abaffc460:  0000000000000000  0000000000000004 
00007f0abaffc470:  00007f0aa0011be0  0000000000000000 
00007f0abaffc480:  00007f0abaffc4f0  00007f0ad6bf9afc 
00007f0abaffc490:  0000000000000004  0000000000000000 
00007f0abaffc4a0:  0000000000000004  00007f0ad6bb68e5 
00007f0abaffc4b0:  0000000000000000  0000000000000000 
00007f0abaffc4c0:  0000000000000004  0000000000000004 
00007f0abaffc4d0:  0000000000000004  00007f0ad6bb5c68 
00007f0abaffc4e0: <0000000000000000  00007f0ad6bb6d0d 
00007f0abaffc4f0:  00007f0ad6c0565a  00007f0ad6c5caa2 
00007f0abaffc500:  ffffffffffffffff  00007f0ad6c0558f 
00007f0abaffc510:  00007f0aa0014110  ffffffffffffffff 
00007f0abaffc520:  00007f0ad6c055a2  00007f0ad6bff21b 
00007f0abaffc530:  ffffffffffffffff  00007f0ad6c055fc 
00007f0abaffc540:  00007f0ad66d84e7  ffffffffffffffff 
00007f0abaffc550:  0000000000000000  b85d9a16de3d8600 
00007f0abaffc560:  0000000000000004  00007f0ad6bb6f5f 
00007f0abaffc570:  00007f0aa0014110  00000001a00018b0 
00007f0abaffc580:  00007f0ad6bb6c60  0000000000000000 
00007f0abaffc590:  00007f0ad66d84e7  00007f0ad66d84e7 
00007f0abaffc5a0:  00007f0aa0004d20  00007f0aa00018b0 
00007f0abaffc5b0:  00007f0aa0004d20  00007f0aa0004d30 
00007f0abaffc5c0:  0000000000000000  00007f0ad65a12e0 
00007f0abaffc5d0:  00007f0aa0001c10  00007f0ad6561d93 

goroutine 1 [syscall]:
runtime.cgocall(0x7d7e30, 0xc00013fc98, 0x16)
	/usr/lib/go-1.11/src/runtime/cgocall.go:128 +0x5e fp=0xc00013fc68 sp=0xc00013fc30 pc=0x43837e
pkg.deepin.io/gir/gio-2%2e0._Cfunc_g_settings_new(0x7f0aa0013990, 0x0)
	_cgo_gotypes.go:8445 +0x4a fp=0xc00013fc98 sp=0xc00013fc68 pc=0x6c9ada
pkg.deepin.io/gir/gio-2%2e0.NewSettings(0x8e7576, 0x16, 0x0)
	/usr/share/gocode/src/pkg.deepin.io/gir/gio-2.0/gio.go:10112 +0x76 fp=0xc00013fcc8 sp=0xc00013fc98 pc=0x6cb366
pkg.deepin.io/dde/startdde/display.newManager(0xc00005a120, 0xc00005a120)
	/build/startdde-5.5.0.7/gopath/src/pkg.deepin.io/dde/startdde/display/manager.go:160 +0x142 fp=0xc00013fdf0 sp=0xc00013fcc8 pc=0x786702
pkg.deepin.io/dde/startdde/display.Start(0x8e33aa, 0xf)
	/build/startdde-5.5.0.7/gopath/src/pkg.deepin.io/dde/startdde/display/display.go:25 +0xcd fp=0xc00013fe80 sp=0xc00013fdf0 pc=0x78243d
main.main()
	/build/startdde-5.5.0.7/main.go:110 +0x678 fp=0xc00013ff98 sp=0xc00013fe80 pc=0x7cd5e8
runtime.main()
	/usr/lib/go-1.11/src/runtime/proc.go:201 +0x207 fp=0xc00013ffe0 sp=0xc00013ff98 pc=0x461b07
runtime.goexit()
	/usr/lib/go-1.11/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00013ffe8 sp=0xc00013ffe0 pc=0x48d061

goroutine 19 [chan receive]:
pkg.deepin.io/lib/pulse.startHandleSafeDo()
	/usr/share/gocode/src/pkg.deepin.io/lib/pulse/mainloop_callbacks.go:24 +0x4f
created by pkg.deepin.io/lib/pulse.init.0
	/usr/share/gocode/src/pkg.deepin.io/lib/pulse/mainloop_callbacks.go:37 +0x35

goroutine 20 [syscall]:
os/signal.signal_recv(0x0)
	/usr/lib/go-1.11/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/lib/go-1.11/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/lib/go-1.11/src/os/signal/signal_unix.go:29 +0x41

goroutine 21 [IO wait]:
internal/poll.runtime_pollWait(0x7f0ad08ce950, 0x72, 0xc00002d440)
	/usr/lib/go-1.11/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc0000e1918, 0x72, 0xffffffffffffff00, 0x947100, 0xc825b8)
	/usr/lib/go-1.11/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc0000e1918, 0xc0000ed000, 0x1000, 0x1000)
	/usr/lib/go-1.11/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc0000e1900, 0xc0000ed000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.11/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc0000e1900, 0xc0000ed000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.11/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00008c738, 0xc0000ed000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.11/src/net/net.go:177 +0x68
bufio.(*Reader).Read(0xc00008efc0, 0xc0000161a0, 0x20, 0x20, 0x20, 0xc0000161a0, 0x0)
	/usr/lib/go-1.11/src/bufio/bufio.go:216 +0x22f
io.ReadAtLeast(0x946200, 0xc00008efc0, 0xc0000161a0, 0x20, 0x20, 0x20, 0x83cba0, 0x1, 0xc0000161a0)
	/usr/lib/go-1.11/src/io/io.go:310 +0x88
io.ReadFull(0x946200, 0xc00008efc0, 0xc0000161a0, 0x20, 0x20, 0x20, 0x0, 0x0)
	/usr/lib/go-1.11/src/io/io.go:329 +0x58
github.com/linuxdeepin/go-x11-client.(*Conn).readPacket(0xc0000ca2c0, 0x0, 0x0)
	/usr/share/gocode/src/github.com/linuxdeepin/go-x11-client/conn_in.go:63 +0xad
github.com/linuxdeepin/go-x11-client.(*Conn).readLoop(0xc0000ca2c0)
	/usr/share/gocode/src/github.com/linuxdeepin/go-x11-client/conn_in.go:52 +0x2b
created by github.com/linuxdeepin/go-x11-client.NewConnDisplay
	/usr/share/gocode/src/github.com/linuxdeepin/go-x11-client/conn_connect.go:29 +0x1ca

goroutine 22 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc000091bd0, 0x0)
	/usr/lib/go-1.11/src/runtime/sema.go:510 +0xeb
sync.(*Cond).Wait(0xc000091bc0)
	/usr/lib/go-1.11/src/sync/cond.go:56 +0x92
github.com/linuxdeepin/go-x11-client.(*Conn).waitForEvent(0xc0000ca2c0, 0x0, 0x0, 0x0)
	/usr/share/gocode/src/github.com/linuxdeepin/go-x11-client/conn_in.go:336 +0x38
github.com/linuxdeepin/go-x11-client.(*Conn).eventSendLoop(0xc0000ca2c0)
	/usr/share/gocode/src/github.com/linuxdeepin/go-x11-client/conn_in.go:344 +0x75
created by github.com/linuxdeepin/go-x11-client.NewConnDisplay
	/usr/share/gocode/src/github.com/linuxdeepin/go-x11-client/conn_connect.go:30 +0x1ec

goroutine 23 [IO wait]:
internal/poll.runtime_pollWait(0x7f0ad08ce880, 0x72, 0xc000089a60)
	/usr/lib/go-1.11/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc0000e1b98, 0x72, 0xc000162000, 0x1000, 0x0)
	/usr/lib/go-1.11/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc0000e1b98, 0xc000089a00, 0x10, 0x10)
	/usr/lib/go-1.11/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).ReadMsg(0xc0000e1b80, 0xc000089a60, 0x10, 0x10, 0xc000162020, 0x1000, 0x1000, 0x0, 0x0, 0x0, ...)
	/usr/lib/go-1.11/src/internal/poll/fd_unix.go:243 +0x200
net.(*netFD).readMsg(0xc0000e1b80, 0xc000089a60, 0x10, 0x10, 0xc000162020, 0x1000, 0x1000, 0xc0000d1dc0, 0x66711e, 0xc0000d1d20, ...)
	/usr/lib/go-1.11/src/net/fd_unix.go:214 +0x90
net.(*UnixConn).readMsg(0xc00008c748, 0xc000089a60, 0x10, 0x10, 0xc000162020, 0x1000, 0x1000, 0xc864b6, 0xc00025ae40, 0xc000089928, ...)
	/usr/lib/go-1.11/src/net/unixsock_posix.go:115 +0x91
net.(*UnixConn).ReadMsgUnix(0xc00008c748, 0xc000089a60, 0x10, 0x10, 0xc000162020, 0x1000, 0x1000, 0x7, 0xc864b3, 0x203000, ...)
	/usr/lib/go-1.11/src/net/unixsock.go:140 +0xa8
pkg.deepin.io/lib/dbus1.(*oobReader).Read(0xc000162000, 0xc000089a60, 0x10, 0x10, 0x18, 0xc00025b1e0, 0x0)
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus1/transport_unix.go:21 +0x8f
io.ReadAtLeast(0x946a80, 0xc000162000, 0xc000089a60, 0x10, 0x10, 0x10, 0x8328c0, 0xc000001b01, 0xc00025b1e0)
	/usr/lib/go-1.11/src/io/io.go:310 +0x88
io.ReadFull(0x946a80, 0xc000162000, 0xc000089a60, 0x10, 0x10, 0xc0000560d0, 0x0, 0x0)
	/usr/lib/go-1.11/src/io/io.go:329 +0x58
pkg.deepin.io/lib/dbus1.(*unixTransport).ReadMessage(0xc000129360, 0xc000000002, 0x2, 0xc0000c5e01)
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus1/transport_unix.go:91 +0x10f
pkg.deepin.io/lib/dbus1.(*Conn).inWorker(0xc0000ee7e0)
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus1/conn.go:293 +0x37
created by pkg.deepin.io/lib/dbus1.(*Conn).Auth
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus1/auth.go:118 +0x76f

goroutine 25 [IO wait]:
internal/poll.runtime_pollWait(0x7f0ad08ce6e0, 0x72, 0xc0000897f0)
	/usr/lib/go-1.11/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc0000e1d98, 0x72, 0xc00024a000, 0x1000, 0x0)
	/usr/lib/go-1.11/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc0000e1d98, 0xc000089700, 0x10, 0x10)
	/usr/lib/go-1.11/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).ReadMsg(0xc0000e1d80, 0xc0000897f0, 0x10, 0x10, 0xc00024a020, 0x1000, 0x1000, 0x0, 0x0, 0x0, ...)
	/usr/lib/go-1.11/src/internal/poll/fd_unix.go:243 +0x200
net.(*netFD).readMsg(0xc0000e1d80, 0xc0000897f0, 0x10, 0x10, 0xc00024a020, 0x1000, 0x1000, 0xc0000d5dc0, 0x66711e, 0xc0000d5d20, ...)
	/usr/lib/go-1.11/src/net/fd_unix.go:214 +0x90
net.(*UnixConn).readMsg(0xc00008c7c8, 0xc0000897f0, 0x10, 0x10, 0xc00024a020, 0x1000, 0x1000, 0xc864b3, 0xc00025a540, 0xc000089650, ...)
	/usr/lib/go-1.11/src/net/unixsock_posix.go:115 +0x91
net.(*UnixConn).ReadMsgUnix(0xc00008c7c8, 0xc0000897f0, 0x10, 0x10, 0xc00024a020, 0x1000, 0x1000, 0x7f0ad53384c8, 0x17f, 0x203000, ...)
	/usr/lib/go-1.11/src/net/unixsock.go:140 +0xa8
pkg.deepin.io/lib/dbus1.(*oobReader).Read(0xc00024a000, 0xc0000897f0, 0x10, 0x10, 0x18, 0xc00025aa40, 0x0)
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus1/transport_unix.go:21 +0x8f
io.ReadAtLeast(0x946a80, 0xc00024a000, 0xc0000897f0, 0x10, 0x10, 0x10, 0x8328c0, 0x45ee01, 0xc00025aa40)
	/usr/lib/go-1.11/src/io/io.go:310 +0x88
io.ReadFull(0x946a80, 0xc00024a000, 0xc0000897f0, 0x10, 0x10, 0xc000091d40, 0xc0000896d0, 0xc)
	/usr/lib/go-1.11/src/io/io.go:329 +0x58
pkg.deepin.io/lib/dbus1.(*unixTransport).ReadMessage(0xc000129640, 0xc000124bd0, 0x4, 0xc0000c5d01)
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus1/transport_unix.go:91 +0x10f
pkg.deepin.io/lib/dbus1.(*Conn).inWorker(0xc0000ee900)
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus1/conn.go:293 +0x37
created by pkg.deepin.io/lib/dbus1.(*Conn).Auth
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus1/auth.go:118 +0x76f

goroutine 34 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x17d7, 0xc00003ec28, 0x1000004, 0x0, 0x0, 0x60, 0xc0000725a0, 0x0)
	/usr/lib/go-1.11/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc000085920, 0x5, 0xc00003ed90, 0xc000085920)
	/usr/lib/go-1.11/src/os/wait_waitid.go:31 +0x98
os.(*Process).wait(0xc000085920, 0x1, 0x7, 0x0)
	/usr/lib/go-1.11/src/os/exec_unix.go:22 +0x39
os.(*Process).Wait(0xc000085920, 0x8f6908, 0x8f6910, 0x8f6900)
	/usr/lib/go-1.11/src/os/exec.go:125 +0x2b
os/exec.(*Cmd).Wait(0xc0000ca420, 0x0, 0x0)
	/usr/lib/go-1.11/src/os/exec/exec.go:465 +0x5b
os/exec.(*Cmd).Run(0xc0000ca420, 0x9, 0xc0001d2670)
	/usr/lib/go-1.11/src/os/exec/exec.go:309 +0x5c
main.startPulseAudio(0x0, 0x0)
	/build/startdde-5.5.0.7/sound_effect.go:146 +0xa8
main.playLoginSound()
	/build/startdde-5.5.0.7/sound_effect.go:41 +0x37
created by main.main
	/build/startdde-5.5.0.7/main.go:95 +0x138

goroutine 35 [chan receive]:
main.handleSignal()
	/build/startdde-5.5.0.7/main.go:166 +0x117
created by main.main
	/build/startdde-5.5.0.7/main.go:96 +0x150

goroutine 37 [IO wait]:
internal/poll.runtime_pollWait(0x7f0ad08ce7b0, 0x72, 0xc0001aa930)
	/usr/lib/go-1.11/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000172418, 0x72, 0xc00021c600, 0x1000, 0x0)
	/usr/lib/go-1.11/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000172418, 0xc0001aa900, 0x10, 0x10)
	/usr/lib/go-1.11/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).ReadMsg(0xc000172400, 0xc0001aa930, 0x10, 0x10, 0xc00021c620, 0x1000, 0x1000, 0x0, 0x0, 0x0, ...)
	/usr/lib/go-1.11/src/internal/poll/fd_unix.go:243 +0x200
net.(*netFD).readMsg(0xc000172400, 0xc0001aa930, 0x10, 0x10, 0xc00021c620, 0x1000, 0x1000, 0xc000215c98, 0x5e2b02, 0x85ae80, ...)
	/usr/lib/go-1.11/src/net/fd_unix.go:214 +0x90
net.(*UnixConn).readMsg(0xc00017a018, 0xc0001aa930, 0x10, 0x10, 0xc00021c620, 0x1000, 0x1000, 0x4c6010, 0xc0001b7620, 0xc0001aa86c, ...)
	/usr/lib/go-1.11/src/net/unixsock_posix.go:115 +0x91
net.(*UnixConn).ReadMsgUnix(0xc00017a018, 0xc0001aa930, 0x10, 0x10, 0xc00021c620, 0x1000, 0x1000, 0x7, 0xc864b3, 0x203000, ...)
	/usr/lib/go-1.11/src/net/unixsock.go:140 +0xa8
pkg.deepin.io/lib/dbus.(*oobReader).Read(0xc00021c600, 0xc0001aa930, 0x10, 0x10, 0x1020, 0xc00021c600, 0x0)
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus/transport_unix.go:38 +0x8f
io.ReadAtLeast(0x946940, 0xc00021c600, 0xc0001aa930, 0x10, 0x10, 0x10, 0x890300, 0x82e701, 0xc00021c600)
	/usr/lib/go-1.11/src/io/io.go:310 +0x88
io.ReadFull(0x946940, 0xc00021c600, 0xc0001aa930, 0x10, 0x10, 0x0, 0x0, 0x0)
	/usr/lib/go-1.11/src/io/io.go:329 +0x58
pkg.deepin.io/lib/dbus.(*unixTransport).ReadMessage(0xc00017e4a0, 0xc00017c150, 0x2, 0xc0001a0098)
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus/transport_unix.go:98 +0x112
pkg.deepin.io/lib/dbus.(*Conn).inWorker(0xc000188240)
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus/conn.go:276 +0x4b
created by pkg.deepin.io/lib/dbus.(*Conn).Auth
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus/auth.go:139 +0x769

goroutine 38 [chan receive]:
pkg.deepin.io/lib/dbus.(*Conn).outWorker(0xc000188240)
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus/conn.go:398 +0x63
created by pkg.deepin.io/lib/dbus.(*Conn).Auth
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus/auth.go:140 +0x78e

goroutine 4 [chan receive]:
pkg.deepin.io/lib/dbus.(*signalChannel).run(0xc0002280f0)
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus/signal_channel.go:71 +0x283
created by pkg.deepin.io/lib/dbus.newSignalChannel
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus/signal_channel.go:33 +0x120

goroutine 5 [chan receive]:
pkg.deepin.io/lib/gsettings.StartMonitor.func1(0xc00023e060)
	/usr/share/gocode/src/pkg.deepin.io/lib/gsettings/monitor.go:103 +0x42
created by pkg.deepin.io/lib/gsettings.StartMonitor
	/usr/share/gocode/src/pkg.deepin.io/lib/gsettings/monitor.go:102 +0xc6

rax    0x0
rbx    0x1
rcx    0x7f0aa00008d0
rdx    0x1
rdi    0x1
rsi    0x0
rbp    0x4
rsp    0x7f0abaffc4e0
r8     0x7f
r9     0x7f0aa0015640
r10    0x4
r11    0x0
r12    0x4
r13    0x4
r14    0x6
r15    0x2
rip    0x7f0ad6bb5c75
rflags 0x202
cs     0x33
fs     0x0
gs     0x0

```

**Comment by Cardellino** [comment]
Thank you very much for your support James ....
I was able to log in via the console and then start the system upgrade ... Now the login works again ...
Thank you again....

Hello felixonmars, 
thank you very much for the quick response to the troubleshooting ....
Well done......

I wish you both a nice day
Ciao
