### ISSUE TITLE
Bug report 「缺陷报告」qt5integration 5.5.17 crashes 

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/developer-center#2242]
gdb backtrace of deepin-system-monitor

```
(gdb) bt
#0  0x00007fffef835adf in ?? () from /usr/lib64/libpcre2-16.so.0
#1  0x00007fffef85d6de in pcre2_jit_match_16 () from /usr/lib64/libpcre2-16.so.0
#2  0x00007fffef863170 in pcre2_match_16 () from /usr/lib64/libpcre2-16.so.0
#3  0x00007ffff4212e06 in ?? () from /usr/lib64/libQt5Core.so.5
#4  0x00007ffff421722f in QRegularExpression::match(QString const&, int, QRegularExpression::MatchType, QFlags<QRegularExpression::MatchOption>) const () from /usr/lib64/libQt5Core.so.5
#5  0x00007fffd6d7a1b0 in DPluginLoader::pluginName(QString const&) ()
   from /usr/lib64/qt5/plugins/iconengines/libdsvgicon.so
#6  0x00007fffd6d7aaa9 in QIconEnginePlugin* DPluginLoader::load<QIconEnginePlugin>(QString const&)
    () from /usr/lib64/qt5/plugins/iconengines/libdsvgicon.so
#7  0x00007fffd6d795d6 in QSvgIconPlugin::QSvgIconPlugin(QObject*) ()
   from /usr/lib64/qt5/plugins/iconengines/libdsvgicon.so
#8  0x00007fffd6d796bf in qt_plugin_instance ()
   from /usr/lib64/qt5/plugins/iconengines/libdsvgicon.so
#9  0x00007ffff430de06 in QPluginLoader::instance() () from /usr/lib64/libQt5Core.so.5
#10 0x00007fffd6d7acc0 in QIconEnginePlugin* DPluginLoader::load<QIconEnginePlugin>(QString const&)
    () from /usr/lib64/qt5/plugins/iconengines/libdsvgicon.so
#11 0x00007fffd6d795d6 in QSvgIconPlugin::QSvgIconPlugin(QObject*) ()
   from /usr/lib64/qt5/plugins/iconengines/libdsvgicon.so
#12 0x00007fffd6d796bf in qt_plugin_instance ()
   from /usr/lib64/qt5/plugins/iconengines/libdsvgicon.so
#13 0x00007ffff430de06 in QPluginLoader::instance() () from /usr/lib64/libQt5Core.so.5
#14 0x00007fffd6d7acc0 in QIconEnginePlugin* DPluginLoader::load<QIconEnginePlugin>(QString const&)
    () from /usr/lib64/qt5/plugins/iconengines/libdsvgicon.so
#15 0x00007fffd6d795d6 in QSvgIconPlugin::QSvgIconPlugin(QObject*) ()
   from /usr/lib64/qt5/plugins/iconengines/libdsvgicon.so
#16 0x00007fffd6d796bf in qt_plugin_instance ()
   from /usr/lib64/qt5/plugins/iconengines/libdsvgicon.so
#17 0x00007ffff430de06 in QPluginLoader::instance() () from /usr/lib64/libQt5Core.so.5
#18 0x00007fffd6d7acc0 in QIconEnginePlugin* DPluginLoader::load<QIconEnginePlugin>(QString const&)
    () from /usr/lib64/qt5/plugins/iconengines/libdsvgicon.so
#19 0x00007fffd6d795d6 in QSvgIconPlugin::QSvgIconPlugin(QObject*) ()
```

**Comment by hillwoodroc** [comment]
There is a same report: https://github.com/linuxdeepin/developer-center/issues/2242

**Comment by hillwoodroc** [comment]
Removing libdsvgicon.so can workaround this issue.

**Comment by justforlxz** [comment]
try add BASED_DTK_DIR=based-dtk to qmake

**Comment by justforlxz** [comment]
solved
