### ISSUE TITLE
Segmentation fault on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/developer-center#2290]
version: 5.2.0.87

```
(gdb) bt
#0  0x00007ffff7b6828b in dde_file_manager::DFMEventDispatcher::installEventHandler(dde_file_manager::DFMAbstractEventHandler*) ()
   from /usr/lib64/libdde-file-manager.so.1
linuxdeepin/dde-file-manager#1  0x00007ffff7b683ce in dde_file_manager::FileEventProcessor::FileEventProcessor() () from /usr/lib64/libdde-file-manager.so.1
linuxdeepin/dde-file-manager#2  0x00007ffff789e5ab in ?? () from /usr/lib64/libdde-file-manager.so.1
linuxdeepin/dde-file-manager#3  0x00007ffff7fdc43e in call_init.part () from /lib64/ld-linux-x86-64.so.2
linuxdeepin/dde-file-manager#4  0x00007ffff7fdc528 in _dl_init () from /lib64/ld-linux-x86-64.so.2
linuxdeepin/dde-file-manager#5  0x00007ffff7fcd0ca in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
linuxdeepin/dde-file-manager#6  0x0000000000000001 in ?? ()
linuxdeepin/dde-file-manager#7  0x00007fffffffe385 in ?? ()
linuxdeepin/dde-file-manager#8  0x0000000000000000 in ?? ()

```

**Comment by tsic404** [comment]
duplicate #2291
