### ISSUE TITLE
deepin-launcher 4.1.9-1 無法開啟

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#375]
```
Thread 8 (Thread 0x7fffcd31a700 (LWP 1346)):
#0  0x00007ffff47f1e0a in semop () at /usr/lib/libc.so.6
#1  0x00007ffff533ce1e in  () at /usr/lib/libQt5Core.so.5
#2  0x00007ffff7a8f804 in non-virtual thunk to QtConcurrent::RunFunctionTask<void>::run() ()
    at /usr/lib/libdtkwidget.so.2
#3  0x00007ffff50f71b1 in  () at /usr/lib/libQt5Core.so.5
#4  0x00007ffff50fafcb in  () at /usr/lib/libQt5Core.so.5
#5  0x00007ffff1f1908a in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff47f024f in clone () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7fffcffff700 (LWP 1344)):
#0  0x00007ffff47e5d4b in poll () at /usr/lib/libc.so.6
#1  0x00007ffff333bed3 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff333bfae in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff5339cd1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#4  0x00007ffff52dd48b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#5  0x00007ffff50f627e in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007ffff5755376 in  () at /usr/lib/libQt5DBus.so.5
#7  0x00007ffff50fafcb in  () at /usr/lib/libQt5Core.so.5
#8  0x00007ffff1f1908a in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007ffff47f024f in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7fffdbfff700 (LWP 1343)):
#0  0x00007ffff47e5d4b in poll () at /usr/lib/libc.so.6
#1  0x00007ffff75738e0 in  () at /usr/lib/libxcb.so.1
---Type <return> to continue, or q <return> to quit---
#2  0x00007ffff7575679 in xcb_wait_for_event () at /usr/lib/libxcb.so.1
#3  0x00007fffe28fb85a in  () at /usr/lib/libQt5XcbQpa.so.5
#4  0x00007ffff50fafcb in  () at /usr/lib/libQt5Core.so.5
#5  0x00007ffff1f1908a in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff47f024f in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7fffe3611700 (LWP 1342)):
#0  0x00007ffff47e5d4b in poll () at /usr/lib/libc.so.6
#1  0x00007ffff333bed3 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff333cf42 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff2192e28 in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007ffff33301eb in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff1f1908a in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff47f024f in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7fffe3fff700 (LWP 1341)):
#0  0x00007ffff47e5d4b in poll () at /usr/lib/libc.so.6
#1  0x00007ffff333bed3 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff333bfae in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff333c002 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff33301eb in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff1f1908a in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff47f024f in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7fffe89e9700 (LWP 1340)):
#0  0x00007ffff47e5d4b in poll () at /usr/lib/libc.so.6
#1  0x00007ffff333bed3 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff333bfae in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#3  0x00007fffe89f0b0e in  () at /usr/lib/gio/modules/libdconfsettings.so
#4  0x00007ffff33301eb in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff1f1908a in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff47f024f in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff7f95980 (LWP 1336)):
#0  0x00007ffff47e5d4b in poll () at /usr/lib/libc.so.6
#1  0x00007ffff333bed3 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff333bfae in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff5339cd1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#4  0x00007ffff52dd48b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#5  0x00007ffff52e64d8 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#6  0x0000555555578b6c in main ()
```

**Comment by felixonmars** [comment]
Please try deepin-desktop-schemas 3.1.17.20171013-1

**Comment by JulianLai** [comment]
已修復
