### ISSUE TITLE
出大包了，更新過後 dde-dock 無法使用

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#407]
目前找到可以暫時回復正常的方法是先使用 deepin-screen-recorder 錄製 gif，然後 Ctrl+T 開啟 terminal，這樣才能回復正常，但登出再登入後就變回這樣了，而且這方法還不一定會有效果，還會時不時地消失
![deepin _20171116230329](https://user-images.githubusercontent.com/20014762/32898249-93919b9a-cb22-11e7-8b36-94c7597ba81e.png)
![deepin-screen-recorder_desktop_20171116231618](https://user-images.githubusercontent.com/20014762/32898887-5e7cab50-cb24-11e7-904c-103f2b57b647.gif)

**Comment by felixonmars** [comment]
我这里重现不出来……可以考虑过一会再等几个更新试试有没有变化。

**Comment by JulianLai** [comment]
@felixonmars 把 dde-dock 降級就解決了

**Comment by felixonmars** [comment]
@sbwtw

**Comment by JulianLai** [comment]
@felixonmars 這是用 gdb 跑完後輸入 bt 的結果
```
#0  0x00007ffff4afdf7b in poll () at /usr/lib/libc.so.6
#1  0x00007ffff322ced3 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff322cfae in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff599ecd1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#4  0x00007ffff594248b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#5  0x00007ffff594b4d8 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#6  0x000055555556cfac in main ()
```

**Comment by sbwtw** [comment]
emmmm... 有没有试过编译安装呢

**Comment by hualet** [comment]
应该不是Dock崩溃了，而是位置移动错误了 @sbwtw @zccrs

**Comment by zccrs** [comment]
贴一下这个输出：
xprop -root|grep -i _NET_CLIENT_LIST_STACKING\(WINDOW\)|awk '{print $NF}'|xargs xwininfo -id

**Comment by sbwtw** [comment]
https://cr.deepin.io/#/c/28595/ @felixonmars @JulianLai 可以帮忙测试这个提交吗

**Comment by JulianLai** [comment]
@sbwtw 
```
xwininfo: Window id: 0x1e00009 "DDE Dock"

  Absolute upper-left X:  341
  Absolute upper-left Y:  948
  Relative upper-left X:  341
  Relative upper-left Y:  948
  Width: 1238
  Height: 192
  Depth: 32
  Visual: 0x74
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x1e00008 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +341+948  -341+948  -341--60  +341--60
  -geometry 1238x192+341--60
```

**Comment by sbwtw** [comment]
@JulianLai 这个问题已经解决了，请更新到 4.5.1

**Comment by JulianLai** [comment]
@sbwtw 結果更糟糕了
![deepin _20171117122632](https://user-images.githubusercontent.com/20014762/32929397-b36144f0-cb92-11e7-85c3-97b0ee6464c3.png)

**Comment by JulianLai** [comment]
如果是這個模式就不會發生：
![deepin _20171117135356](https://user-images.githubusercontent.com/20014762/32931369-c560c0ac-cb9e-11e7-8eed-448de86ec9e2.png)
只有 dock 的會那樣

**Comment by sbwtw** [comment]
@JulianLai 不正常的时候位置应该是 60, 60 吧？
这有可能是另一个问题 @zccrs

**Comment by JulianLai** [comment]
不曉得要怎麼知道他的座標，一開始位置是選擇底部（不正常），再來選擇頂部（不正常），然後選擇底部就正常了

**Comment by zccrs** [comment]
@JulianLai 使用xwininfo后点击dock窗口就可以获取窗口信息，可以尝试把dock固定在上面或者右边，查看注销再进来dock位置是否正确

**Comment by JulianLai** [comment]
@zccrs 不正確

**Comment by JulianLai** [comment]
@zccrs 三次用 xwininfo 側到得結果如下
第一次（底部）：
```
xwininfo: Window id: 0x2600009 "DDE Dock"

  Absolute upper-left X:  0
  Absolute upper-left Y:  0
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 1238
  Height: 192
  Depth: 32
  Visual: 0x74
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x2600008 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +0+0  -682+0  -682-888  +0-888
  -geometry 1238x192+0+0
```
第二次（右側）：
```
xwininfo: Window id: 0x2600009 "DDE Dock"

  Absolute upper-left X:  0
  Absolute upper-left Y:  0
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 199
  Height: 1140
  Depth: 32
  Visual: 0x74
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x2600008 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +0+0  -1721+0  -1721--60  +0--60
  -geometry 199x1140+0+0
```
第三次（底部）：
```
xwininfo: Window id: 0x2600009 "DDE Dock"

  Absolute upper-left X:  341
  Absolute upper-left Y:  948
  Relative upper-left X:  341
  Relative upper-left Y:  948
  Width: 1238
  Height: 192
  Depth: 32
  Visual: 0x74
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x2600008 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +341+948  -341+948  -341--60  +341--60
  -geometry 1238x192+341--60
```

**Comment by zccrs** [comment]
@JulianLai 使用高效模式呢？计入桌面后使用 xkill 杀掉dock，看之后再出现的dock位置是否正确

**Comment by JulianLai** [comment]
@zccrs 高效不會，只有 dock 會，xkill 後就出現錯誤結果

**Comment by zccrs** [comment]
@JulianLai  killall dde-dock; dde-dock -platform xcb 试一下这样出现的dock位置是否正确

**Comment by JulianLai** [comment]
@zccrs 正確

**Comment by zccrs** [comment]
@JulianLai  qt5dxcb-plugin和libdeepin-mutter0g的版本

**Comment by JulianLai** [comment]
@zccrs 
```
名稱                   : deepin-qt5dxcb-plugin
版本                   : 1.1.2-1
描述                   : Qt platform plugins for DDE
硬體架構               : x86_64
URL                    : https://github.com/linuxdeepin/qt5dxcb-plugin
軟體授權               : GPL3
群組                   : deepin
它提供                 : 無
它依賴                 : qt5-x11extras
可選依賴               : 無
需要它                 : deepin-qt5integration
為這些軟體包的可選依賴 : 無
與它衝突               : 無
它會取代               : 無
安裝後大小             : 371.00 KiB
打包者                 : Felix Yan <felixonmars@archlinux.org>
建置日期               : 西元2017年11月16日 (週四) 17時18分00秒
安裝日期               : 西元2017年11月16日 (週四) 23時42分03秒
安裝原因               : 作為其他軟體包的依賴安裝
安裝指令稿             : 否
驗證者                 : 簽章
```
```
名稱                   : deepin-mutter
版本                   : 3.20.26-1
描述                   : Base window manager for deepin, fork of gnome mutter
硬體架構               : x86_64
URL                    : https://github.com/linuxdeepin/deepin-mutter
軟體授權               : GPL3
群組                   : 無
它提供                 : 無
它依賴                 : deepin-clutter  dconf  gobject-introspection-runtime
                         deepin-desktop-schemas  libcanberra  startup-notification
                         zenity  libsm  gnome-desktop  upower  libxkbcommon-x11
                         libgudev  deepin-cogl
可選依賴               : 無
需要它                 : deepin-wm
為這些軟體包的可選依賴 : 無
與它衝突               : 無
它會取代               : 無
安裝後大小             : 5.16 MiB
打包者                 : Felix Yan <felixonmars@archlinux.org>
建置日期               : 西元2017年11月16日 (週四) 16時50分10秒
安裝日期               : 西元2017年11月16日 (週四) 23時01分11秒
安裝原因               : 單獨指定安裝
安裝指令稿             : 否
驗證者                 : 簽章
```

**Comment by JulianLai** [comment]
沒再出現過
