### ISSUE TITLE
使用 deepin-terminal 遠端管理功能時會崩潰

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#409]
![deepin-screen-recorder_deepin-terminal_20171120132858](https://user-images.githubusercontent.com/20014762/33003634-dcee0112-cdf6-11e7-9ccc-d8e2dd724f99.gif)

backtrace:
```
#0  0x00007ffff528dcd2 in  () at /usr/lib/libglib-2.0.so.0
#1  0x00007ffff528decd in g_log_default_handler () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff528e4ef in g_logv () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff528e680 in g_log () at /usr/lib/libglib-2.0.so.0
#4  0x00005555555b53f9 in widgets_remote_panel_login_server ()
#5  0x00007ffff77f46f5 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff78080b0 in  () at /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff780c696 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff780d920 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff77f46f5 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff78080b0 in  () at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff780c696 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff780d920 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#13 0x00007ffff77f46f5 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#14 0x00007ffff78080b0 in  () at /usr/lib/libgobject-2.0.so.0
#15 0x00007ffff780c696 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#16 0x00007ffff780d920 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#17 0x00005555555871fa in  ()
#18 0x00007ffff70f30fc in  () at /usr/lib/libgtk-3.so.0
#19 0x00007ffff77f46f5 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#20 0x00007ffff78080b0 in  () at /usr/lib/libgobject-2.0.so.0
#21 0x00007ffff780befe in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#22 0x00007ffff780d920 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#23 0x00007ffff7246385 in  () at /usr/lib/libgtk-3.so.0
#24 0x00007ffff70eff5b in  () at /usr/lib/libgtk-3.so.0
---Type <return> to continue, or q <return> to quit---
#25 0x00007ffff70f21b3 in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
#26 0x00007ffff6bfa9f6 in  () at /usr/lib/libgdk-3.so.0
#27 0x00007ffff6c2d375 in  () at /usr/lib/libgdk-3.so.0
#28 0x00007ffff5283270 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#29 0x00007ffff5284f69 in  () at /usr/lib/libglib-2.0.so.0
#30 0x00007ffff5285f42 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#31 0x00007ffff70f127f in gtk_main () at /usr/lib/libgtk-3.so.0
#32 0x00005555555e5dd6 in application_main ()
#33 0x0000555555575770 in main ()
```

**Comment by manateelazycat** [comment]
Has fixed in newest git version.
