### ISSUE TITLE
[go-gir] `checkptr` panics after call to `gio.NewFileForUri`

### ISSUE THREAD

**Issue by denisonbarbosa** [linuxdeepin/developer-center#4276]
### SUMMARY | 问题概要

When trying to create a `gio.File` using the func `gio.NewFileForUri()`, Go errors with `fatal error: checkptr: converted pointer straddles multiple allocations`.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Distribution: Ubuntu 23.04
go: 1.20.4
go-gir: latest (3.0.4)
```

### STEPS TO REPRODUCE | 复现步骤

The code to reproduce the fatal error is quite simple:
```Go
package main

import (
	"github.com/linuxdeepin/go-gir/gio-2.0"
)

func main() {
	_ = gio.FileNewForUri("/tmp/test.txt")
}
```

### ADDITIONAL INFORMATION | 额外补充

Here's the trace of the error:
```
❯ go run -race main.go
# github.com/linuxdeepin/go-gir/gobject-2.0
fix_gobject.c: In function ‘_g_type_param_value_array’:
fix_gobject.c:74:13: warning: Deprecated pre-processor symbol
   74 | GType _g_type_param_value_array()       { return G_TYPE_PARAM_VALUE_ARRAY; }
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fatal error: checkptr: converted pointer straddles multiple allocations

goroutine 1 [running]:
runtime.throw({0x532d4c?, 0x0?})
	/home/denison/go/src/runtime/panic.go:1047 +0x5d fp=0xc0000abeb0 sp=0xc0000abe80 pc=0x46931d
runtime.checkptrAlignment(0x350d570?, 0x350d500?, 0x4f2ee0?)
	/home/denison/go/src/runtime/checkptr.go:26 +0x6c fp=0xc0000abed0 sp=0xc0000abeb0 pc=0x43d76c
github.com/linuxdeepin/go-gir/gio-2%2e0.FileNewForUri({0x52c967, 0xd})
	/home/denison/go/pkg/mod/github.com/linuxdeepin/go-gir@v0.0.0-20230413065249-b60cd1aca477/gio-2.0/gio.go:12616 +0xd5 fp=0xc0000abf60 sp=0xc0000abed0 pc=0x4c4c55
main.main()
	/home/denison/work/go-mount-handler/main.go:8 +0x2f fp=0xc0000abf80 sp=0xc0000abf60 pc=0x4c554f
runtime.main()
	/home/denison/go/src/runtime/proc.go:250 +0x207 fp=0xc0000abfe0 sp=0xc0000abf80 pc=0x46bc07
runtime.goexit()
	/home/denison/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000abfe8 sp=0xc0000abfe0 pc=0x4975a1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x5ea7e0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/denison/go/src/runtime/proc.go:381 +0xd6 fp=0xc0000687b0 sp=0xc000068790 pc=0x46c056
runtime.goparkunlock(...)
	/home/denison/go/src/runtime/proc.go:387
runtime.forcegchelper()
	/home/denison/go/src/runtime/proc.go:305 +0xb0 fp=0xc0000687e0 sp=0xc0000687b0 pc=0x46be90
runtime.goexit()
	/home/denison/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000687e8 sp=0xc0000687e0 pc=0x4975a1
created by runtime.init.6
	/home/denison/go/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/denison/go/src/runtime/proc.go:381 +0xd6 fp=0xc000074f80 sp=0xc000074f60 pc=0x46c056
runtime.goparkunlock(...)
	/home/denison/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/home/denison/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc000074fc8 sp=0xc000074f80 pc=0x458fee
runtime.gcenable.func1()
	/home/denison/go/src/runtime/mgc.go:178 +0x26 fp=0xc000074fe0 sp=0xc000074fc8 pc=0x44e2c6
runtime.goexit()
	/home/denison/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000074fe8 sp=0xc000074fe0 pc=0x4975a1
created by runtime.gcenable
	/home/denison/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000022070?, 0x54c598?, 0x1?, 0x0?, 0x0?)
	/home/denison/go/src/runtime/proc.go:381 +0xd6 fp=0xc00007af70 sp=0xc00007af50 pc=0x46c056
runtime.goparkunlock(...)
	/home/denison/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x5ea3a0)
	/home/denison/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc00007afa0 sp=0xc00007af70 pc=0x456f33
runtime.bgscavenge(0x0?)
	/home/denison/go/src/runtime/mgcscavenge.go:628 +0x45 fp=0xc00007afc8 sp=0xc00007afa0 pc=0x4574e5
runtime.gcenable.func2()
	/home/denison/go/src/runtime/mgc.go:179 +0x26 fp=0xc00007afe0 sp=0xc00007afc8 pc=0x44e266
runtime.goexit()
	/home/denison/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00007afe8 sp=0xc00007afe0 pc=0x4975a1
created by runtime.gcenable
	/home/denison/go/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/denison/go/src/runtime/proc.go:381 +0xd6 fp=0xc000184e28 sp=0xc000184e08 pc=0x46c056
runtime.runfinq()
	/home/denison/go/src/runtime/mfinal.go:193 +0x13d fp=0xc000184fe0 sp=0xc000184e28 pc=0x44d2fd
runtime.goexit()
	/home/denison/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000184fe8 sp=0xc000184fe0 pc=0x4975a1
created by runtime.createfing
	/home/denison/go/src/runtime/mfinal.go:163 +0x45
exit status 2
```

**Comment by dengbo11** [comment]
Thanks for feedback, this bug is fixed in https://github.com/linuxdeepin/go-gir/pull/46

**Comment by dengbo11** [comment]
go-gir is not a mature project, and maybe you can use https://github.com/mattn/go-gtk to meet your needs.
