### ISSUE TITLE
Unable to add PPA ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#442]
Hi,

experiencing problem adding a PPA to the repositories ... error pasted below ...

sudo add-apt-repository ppa:bubbleguuum/bubbleupnpserver
 
 More info: https://launchpad.net/~bubbleguuum/+archive/ubuntu/bubbleupnpserver
Press [ENTER] to continue or ctrl-c to cancel adding it

```
gpg: keybox '/tmp/tmpk50r3l2j/pubring.gpg' created
gpg: /tmp/tmpk50r3l2j/trustdb.gpg: trustdb created
gpg: key 4B5FE5DA1C4E3F4D: public key "Launchpad PPA for Michael Pujos" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.5/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.extra'

```

This has been happening since my very first Deepin experience(since version 15.4) ...

**Comment by felixonmars** [comment]
IMHO PPA is not really supported since Deepin is now based on Debian instead of Ubuntu.

**Comment by aiamuzz** [comment]
Oh ... then how does one get to install apps that require a PPA to be added ?

**Comment by mikegilchrist** [comment]
For the bubbleupnp on an ARMyou need to use optware-ng's ipkg. See https://bubblesoftapps.com/bubbleupnpserver2/docs/linux_install.html and look for optware

**Comment by tsic404** [comment]
PPA is not really supported since Deepin is now based on Debian instead of Ubuntu.
