### ISSUE TITLE
deepin-image-viewer 動不動就當掉

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#464]
```
#0  0x00007ffff344b97b in poll () at /usr/lib/libc.so.6
#1  0x00007ffff631cff3 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff631d10e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff4517b71 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#4  0x00007fffe6f192f2 in  () at /usr/lib/libQt5XcbQpa.so.5
#5  0x00007ffff44b9d0b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#6  0x00007fffdfb95d30 in QDeepinFileDialogHelper::exec() ()
    at /usr/lib/qt/plugins/platformthemes/libqdeepin.so
#7  0x00007ffff5900cd5 in QDialog::exec() () at /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff59137ab in QFileDialog::getExistingDirectoryUrl(QWidget*, QString const&, QUrl const&, QFlags<QFileDialog::Option>, QStringList const&) () at /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff591397b in QFileDialog::getExistingDirectory(QWidget*, QString const&, QString const&, QFlags<QFileDialog::Option>) () at /usr/lib/libQt5Widgets.so.5
#10 0x000055555564c48e in  ()
#11 0x00007ffff44ec00f in QMetaObject::activate(QObject*, int, int, void**) ()
    at /usr/lib/libQt5Core.so.5
#12 0x00007ffff44ec00f in QMetaObject::activate(QObject*, int, int, void**) ()
    at /usr/lib/libQt5Core.so.5
#13 0x00007ffff57ff623 in QAbstractButton::clicked(bool) () at /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff57ff83c in  () at /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff5800c7c in  () at /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff5800e7e in QAbstractButton::mouseReleaseEvent(QMouseEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
#17 0x00007ffff5749e38 in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#18 0x00007ffff5709e3c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#19 0x00007ffff5711d91 in QApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#20 0x00007ffff6f8c59b in Dtk::Widget::DApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/libdtkwidget.so.2
#21 0x00007ffff44bb6c0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /usr/lib/libQt5Core.so.5
#22 0x00007ffff5710d1a in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /usr/lib/libQt5Widgets.so.5
#23 0x00007ffff5765289 in  () at /usr/lib/libQt5Widgets.so.5
#24 0x00007ffff57679a0 in  () at /usr/lib/libQt5Widgets.so.5
#25 0x00007ffff5709e3c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#26 0x00007ffff5711816 in QApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#27 0x00007ffff6f8c59b in Dtk::Widget::DApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/libdtkwidget.so.2
#28 0x00007ffff44bb6c0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /usr/lib/libQt5Core.so.5
#29 0x00007ffff4f00634 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt5Gui.so.5
#30 0x00007ffff4f02186 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/libQt5Gui.so.5
---Type <return> to continue, or q <return> to quit---
#31 0x00007ffff4ed9bbc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#32 0x00007fffe6f192fd in  () at /usr/lib/libQt5XcbQpa.so.5
#33 0x00007ffff44b9d0b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#34 0x00007ffff44c2ff8 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#35 0x00005555555b2cf9 in main ()

```

**Comment by sbwtw** [comment]
@sonald

**Comment by sbwtw** [comment]
@sonald  手滑
@pangpangpang3 @zccrs

**Comment by pangpangpang3** [comment]
有什么特殊的操作导致的吗?

**Comment by pangpangpang3** [comment]
Update: libqt5dxcb-plugin.

Version: 1.1.6+r22~1a8e03c
Provides: libqt5dxcb-plugin

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
